### ISSUE TITLE
Toggle Menu

### ISSUE THREAD

**Issue by MckinstryJ** [TravisGM92/web_proj2#5]
The toggle titles should be more presentable. 

**Title**
In this section you can toggle if you are training the AI or testing it, ....
<toogle>

Note: Do this for both sections. Each section should be aligned on the left edge of each other but still have that middle text style. The toggles should be align with each other as well. =)

**Comment by TravisGM92** [comment]
This has been solved, right?

**Comment by MckinstryJ** [comment]
No it hasn't. If you look at the website these are not align as stated in the note above.

**Comment by TravisGM92** [comment]
My b.
